var itemData = {
    'Other':{
        'Custom':{

        },'Animals - Aquatic':{
            "Blue whale":{"price":1250000,"weight":0,"description":"The imposing blue whale is one of the largest animals in the sea, though it is generally docile toward anything it doesn’t perceive as a threat. A filter-feeder, the blue whale does not look at humans or ships as potential meals, instead preferring to eat millions of tiny invertebrates known as krill, which it sucks through its baleen in massive gulps. The most dangerous thing about a blue whale, other than its sheer size, is its powerful tail, which can capsize boats and kill humanoids. These enormous mammals can be found in all of the world’s oceans and seas. An adult blue whale is 100 feet long and weighs 200 tons.",},
            "Crimson whale":{"price":800000,"weight":0,"description":"While many cetaceans are docile, the crimson whale is an aggressive hunter that evolved to quickly kill even the largest and most powerful of prey. It sports a full set of deadly teeth that average between 1 and 2 feet in length, and its powerful bite can tear through flesh and crush bone. A typical adult crimson whale is 45 feet long and weighs 30 tons.",},
            "Crocodile":{"price":5500,"weight":0,"description":"A crocodile is a primeval reptile that dwells in swamps or along the banks of rivers, a habitat that often puts it in violent contact with unsuspecting prey that come to the water’s edge to drink.",},
            "Dolphin":{"price":10500,"weight":0,"description":"Dolphins are social predators that hunt shallow seas and rivers in large family groups called pods. Sailors are fond of dolphins and frequently tell tales of dolphins saving drowning fishermen or killing sharks with blows from their powerful snouts.",},
            "Dwarf caiman":{"price":700,"weight":0,"description":"Dwarf caimans are a small species of crocodilian predators that live amid the fast-running streams of tropical rainforests and swamps. These patient predators sometimes lie in awkward positions for hours before they strike their prey, their mottled scales disguising them as floating wood.",},
            "Electric eel":{"price":12500,"weight":0,"description":"The electric eel is a curious fish that breathes air instead of water, yet certainly its most unusual characteristic is its ability to generate powerful jolts of electricity. An electric eel is 6 feet long and weighs 45 pounds.",},
            "Gar":{"price":9000,"weight":0,"description":"",},
            "Giant frog":{"price":7500,"weight":0,"description":"",},
            "Giant gar":{"price":120000,"weight":0,"description":"",},
            "Giant moray eel":{"price":100000,"weight":0,"description":"",},
            "Giant octopus":{"price":180000,"weight":0,"description":"",},
            "Giant squid":{"price":250000,"weight":0,"description":"",},
            "Giant toad":{"price":15000,"weight":0,"description":"",},
            "Great white whale":{"price":1260000,"weight":0,"description":"",},
            "Manta ray":{"price":2500,"weight":0,"description":"",},
            "Marine iguana":{"price":600,"weight":0,"description":"",},
            "Narwhal":{"price":35000,"weight":0,"description":"",},
            "Orca":{"price":135000,"weight":0,"description":"",},
            "Sea krait":{"price":500,"weight":0,"description":"",},
            "Seal":{"price":4500,"weight":0,"description":"",},
            "Shark":{"price":32500,"weight":0,"description":"",},
            "Squid":{"price":2500,"weight":0,"description":"",},
            "Stingray":{"price":1800,"weight":0,"description":"",},
            "Whale":{"price":1000000,"weight":0,"description":"",},
        },'Animals - Birds':{
            "Axe beak":{"price":150000,"weight":500,"description":"These Large avian predators are sometimes used as hunting animals but are prized as mounts.",},
            "Axe beak (combat trained)":{"price":150000,"weight":500,"description":"These Large avian predators are sometimes used as hunting animals but are prized as mounts.",},
            "Axe beak egg":{"price":100000,"weight":10,"description":"Axe beaks raised from eggs are easily trained as mounts or used as livestock.",},
            "Canary":{"price":4,"weight":0.75,"description":"These Diminutive birds usually have bright feathers and sing pleasantly. More pragmatically, they are also used in mines to detect bad air, as their small bodies are more sensitive to such things; the warning they provide gives humanoids a chance to escape before succumbing to the danger.",},
            "Chicken":{"price":100,"weight":6,"description":"These domesticated birds are not capable of long distance flights, and are raised for their eggs and meat. Male chickens are kept for mating and occasionally blood sport.",},
            "Duck":{"price":200,"weight":3,"description":"Farm ducks are used for eggs, meat, and down, while wild ducks are hunted for meat. Ducks have the same statistics as ravens.",},
            "Falcon":{"price":4000,"weight":2,"description":"This Tiny, long-winged hawk is a popular hunting bird for nobility. Falcons are technically a subset of hawks but are considered more “noble.” Ownership is denied to commoners in many nations with hierarchical monarchies.",},
            "Hawk":{"price":1800,"weight":2,"description":"This Tiny, short-winged raptor is a popular hunting bird, but is utilized more often by lower nobility than by commoners without titles. Hawks are known for their sharp eyesight and powerful aerial dives.",},
            "Owl":{"price":2000,"weight":2,"description":"These Tiny birds of prey are mainly nocturnal and are known for their keen eyes and near-silent flight. Owls eat small animals and insects, and can be found in nearly any environment. Some farmers create owl homes near fields and barns to control rodent populations. The smartest owls make excellent familiars.",},
            "Owl, ruffled":{"price":2000,"weight":1,"description":"These owls have a distinct “ruffled feather” look on their heads, making them look like sleepy professors in the daytime.",},
            "Parrot":{"price":5000,"weight":4,"description":"These colorful and intelligent birds can be trained to mimic humanoid voices. They are often kept as pets by the wealthy and those who live in the tropical climates they favor. Parrots have the same statistics as ravens.",},
            "Raven":{"price":200,"weight":3,"description":"These Tiny birds are known for their intelligence, and even play games with each other in the wild. They eat insects and can be found in surprisingly varied habitats.",},
            "Thrush":{"price":10,"weight":0.44,"description":"These small plump birds are sometimes kept as pets, but are more often used as familiars for spellcasters. They are known for their beautiful song and their potential for actual speech.",},
        },'Animals - Dinosaurs':{
            "Allosaurus":{"price":385000,"weight":0,"description":"",},
            "Ankylosaurus":{"price":300000,"weight":0,"description":"",},
            "Archelon":{"price":175000,"weight":0,"description":"",},
            "Arsinoitherium":{"price":315000,"weight":0,"description":"",},
            "Baluchitherium":{"price":480000,"weight":0,"description":"",},
            "Basilosaurus":{"price":1020000,"weight":0,"description":"",},
            "Brachiosaurus":{"price":900000,"weight":0,"description":"",},
            "Compsognathus":{"price":2500,"weight":0,"description":"",},
            "Deinonychus":{"price":60000,"weight":0,"description":"",},
            "Dimetrodon":{"price":60000,"weight":0,"description":"",},
            "Elasmosaurus":{"price":350000,"weight":0,"description":"",},
            "Glyptodon":{"price":270000,"weight":0,"description":"",},
            "Iguanodon":{"price":270000,"weight":0,"description":"",},
            "Megalania":{"price":350000,"weight":0,"description":"",},
            "Megaloceros":{"price":80000,"weight":0,"description":"",},
            "Megatherium":{"price":175000,"weight":0,"description":"",},
            "Pachycephalosaurus":{"price":100000,"weight":0,"description":"",},
            "Parasaurolophus":{"price":120000,"weight":0,"description":"",},
            "Pteranodon":{"price":75000,"weight":0,"description":"",},
            "Spinosaurus":{"price":1100000,"weight":0,"description":"",},
            "Stegosaurus":{"price":420000,"weight":0,"description":"",},
            "Triceratops":{"price":560000,"weight":0,"description":"",},
            "Tylosaurus":{"price":400000,"weight":0,"description":"",},
            "Tyrannosaurus":{"price":810000,"weight":0,"description":"",},
        }
    },'Weapons':{
        'Light Melee':{
            "Barbazu beard":{"price":2500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":5,"B":0,"P":0,"S":1,"special":"see text","source":"PPC:Devils","level":"Exotic",},
            "Dagger, swordbreaker":{"price":1000,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":3,"B":0,"P":0,"S":1,"special":"disarm, sunder","source":"PZO1115","level":"Exotic",},
            "Flying Talon":{"price":1500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":10,"weight":5,"B":0,"P":1,"S":0,"special":"disarm, trip","source":"PPZO94102","level":"Exotic",},
            "Helmet, dwarven boulder":{"price":2000,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":10,"B":1,"P":0,"S":0,"special":"see text","source":"PZO1121","level":"Exotic",},
            "Knife, butterfly":{"price":500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":0,"weight":1,"B":0,"P":1,"S":1,"special":0,"source":"PPZO9410","level":"Exotic",},
            "Knife, deer horn":{"price":1000,"sDmg":"1d3","mDmg":"1d4","crit":3,"mincrit":20,"range":20,"weight":3,"B":0,"P":1,"S":0,"special":"blocking, monk","source":"PZO9468","level":"Exotic",},
            "Razor, drow":{"price":2500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":18,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":"See text","source":"PPZO94102","level":"Exotic",},
            "Rope gauntlet":{"price":20,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":0,"source":"PPZO9410","level":"Exotic",},
            "Sai":{"price":100,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":1,"B":1,"P":0,"S":0,"special":"disarm, monk","source":"PZO1110","level":"Exotic",},
            "Sanpkhang":{"price":6000,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":0,"weight":1,"B":0,"P":1,"S":1,"special":"monk, see text","source":"PPZO94102","level":"Exotic",},
            "Whip, scorpion":{"price":500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":3,"B":0,"P":0,"S":1,"special":"disarm, performance, reach, trip","source":"PZO1118","level":"Exotic",},
            "Battle poi":{"price":500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":0,"S":0,"special":0,"source":"PPZO9410","level":"Exotic",},
            "Aklys":{"price":500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":20,"weight":2,"B":1,"P":0,"S":0,"special":"performance, trip","source":"PZO1118","level":"Exotic",},
            "Axe, knuckle":{"price":900,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":"monk, performance","source":"PZO1118","level":"Exotic",},
            "Axe-Gauntlet, Dwarven Light":{"price":1600,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":0,"weight":5,"B":0,"P":0,"S":1,"special":"blocking, disarm","source":"PPC:HftF","level":"Exotic",},
            "Gnome pincher":{"price":1000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":2,"B":1,"P":0,"S":0,"special":"disarm, see text","source":"PZO9468","level":"Exotic",},
            "Halfling rope-shot":{"price":100,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":1,"B":1,"P":0,"S":0,"special":"disarm","source":"PZO9468","level":"Exotic",},
            "Kama":{"price":200,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":"monk, trip","source":"PZO1110","level":"Exotic",},
            "Maulaxe, dwarven":{"price":2500,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":10,"weight":5,"B":0,"P":0,"S":1,"special":0,"source":"PPZO9410","level":"Exotic",},
            "Nunchaku":{"price":200,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":2,"B":1,"P":0,"S":0,"special":"disarm, monk","source":"PZO1110","level":"Exotic",},
            "Quadrens":{"price":800,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":19,"range":0,"weight":2,"B":0,"P":1,"S":0,"special":"performance","source":"PZO1118","level":"Exotic",},
            "Siangham":{"price":300,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":1,"B":0,"P":1,"S":0,"special":"monk","source":"PZO1110","level":"Exotic",},
            "Sica":{"price":1000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":"performance","source":"PZO1118","level":"Exotic",},
            "Thorn bracer":{"price":3000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":3,"B":0,"P":1,"S":0,"special":0,"source":"PCS","level":"Exotic",},
            "War-shield, dwarven":{"price":5000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":8,"B":0,"P":1,"S":1,"special":"See text","source":"PPZO94102","level":"Exotic",},
            "Waveblade":{"price":500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":18,"range":0,"weight":2,"B":0,"P":1,"S":1,"special":"monk, see text","source":"PPZO94102","level":"Exotic",},
            "Sabre, sawtooth":{"price":3500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":0,"source":"PPZO9410","level":"Exotic",},
            "Ratfolk tailblade":{"price":1100,"sDmg":"1d2","mDmg":"1d3","crit":2,"mincrit":20,"range":0,"weight":0.5,"B":0,"P":0,"S":1,"special":0,"source":"PZO1121","level":"Martial",},
            "Shield, light":{"price":"300/900","sDmg":"1d2","mDmg":"1d3","crit":2,"mincrit":20,"range":0,"weight":"special","B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Blade boot":{"price":2500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":1,"S":0,"special":"see text","source":"PPZO9410","level":"Martial",},
            "Cat-o’-nine-tails":{"price":100,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":1,"special":"disarm, nonlethal","source":"PPZO94102","level":"Martial",},
            "Claw blades":{"price":30500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":"see text","source":"PZO1121","level":"Martial",},
            "Dagger, dueling":{"price":1200,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":10,"weight":1,"B":0,"P":1,"S":1,"special":"See text","source":"PPZO94102","level":"Martial",},
            "Hammer, light":{"price":100,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":20,"weight":2,"B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Katar, tri-bladed":{"price":600,"sDmg":"1d3","mDmg":"1d4","crit":4,"mincrit":20,"range":0,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PPZO94102","level":"Martial",},
            "Knife, switchblade":{"price":500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":10,"weight":1,"B":0,"P":1,"S":0,"special":0,"source":"PPZO9410","level":"Martial",},
            "Kukri":{"price":800,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":18,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Martial",},
            "Pick, light":{"price":400,"sDmg":"1d3","mDmg":"1d4","crit":4,"mincrit":20,"range":0,"weight":3,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Sea-knife":{"price":800,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":0,"weight":1,"B":0,"P":0,"S":1,"special":0,"source":"PZO1121","level":"Martial",},
            "Spiked shield, light":{"price":"1300/1900","sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":"special","B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Starknife":{"price":2400,"sDmg":"1d3","mDmg":"1d4","crit":3,"mincrit":20,"range":20,"weight":3,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "War razor":{"price":800,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":0,"weight":1,"B":0,"P":0,"S":1,"special":0,"source":"PZO9226-Revised","level":"Martial",},
            "Axe, boarding":{"price":600,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":0,"weight":3,"B":0,"P":1,"S":1,"special":0,"source":"PPZO94102","level":"Martial",},
            "Axe, throwing":{"price":800,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":10,"weight":2,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Martial",},
            "Dogslicer":{"price":800,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":19,"range":0,"weight":1,"B":0,"P":0,"S":1,"special":"fragile","source":"PZO1121","level":"Martial",},
            "Gladius":{"price":1500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":19,"range":0,"weight":3,"B":0,"P":1,"S":1,"special":"performance","source":"PZO1118","level":"Martial",},
            "Handaxe":{"price":600,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":0,"weight":3,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Martial",},
            "Kobold tail attachment, (sweeper)":{"price":700,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":3,"B":1,"P":0,"S":0,"special":"trip","source":"PZO1121","level":"Martial",},
            "Kobold tail attachment, long lash":{"price":1500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":1,"special":"reach","source":"PZO1121","level":"Martial",},
            "Machete":{"price":1000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":19,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":0,"source":"PZO9468","level":"Martial",},
            "Sap":{"price":100,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":2,"B":1,"P":0,"S":0,"special":"nonlethal","source":"PZO1110","level":"Martial",},
            "Spiked armor":{"price":"0eial","sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":"special","B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Sword, short":{"price":1000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":19,"range":0,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Kobold tail attachment, (pounder)":{"price":100,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":4,"B":1,"P":0,"S":0,"special":0,"source":"PZO1121","level":"Martial",},
            "Kobold tail attachment, (razored)":{"price":300,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":0,"source":"PZO1121","level":"Martial",},
            "Kobold tail attachment, (spiked)":{"price":300,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PZO1121","level":"Martial",},
            "Handwraps":{"price":10,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":0,"B":0,"P":0,"S":0,"special":"See text","source":"PPC:MAH","level":"Simple",},
            "Brass knuckles":{"price":100,"sDmg":"1d2","mDmg":"1d3","crit":2,"mincrit":20,"range":0,"weight":1,"B":1,"P":0,"S":0,"special":"monk","source":"PPZO9410/PZO1115","level":"Simple",},
            "Brass knife":{"price":200,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":10,"weight":1,"B":0,"P":1,"S":1,"special":"fragile","source":"PPC:Pirates","level":"Simple",},
            "Cestus":{"price":500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":0,"weight":1,"B":0,"P":1,"S":0,"special":"monk","source":"PZO1115","level":"Simple",},
            "Dagger":{"price":200,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":10,"weight":1,"B":0,"P":1,"S":1,"special":0,"source":"PZO1110","level":"Simple",},
            "Dagger, punching":{"price":200,"sDmg":"1d3","mDmg":"1d4","crit":3,"mincrit":20,"range":0,"weight":1,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Gauntlet, spiked":{"price":500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":1,"B":0,"P":1,"S":0,"special":"Attached","source":"PZO1110","level":"Simple",},
            "Hook hand":{"price":1000,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":1,"special":"disarm, attached, see text","source":"PPC:Pirates","level":"Simple",},
            "Kunai":{"price":200,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":10,"weight":2,"B":0,"P":1,"S":0,"special":"tool","source":"PPC:RTT","level":"Simple",},
            "Spring blade":{"price":7000,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":10,"weight":1,"B":0,"P":1,"S":1,"special":"see text","source":"PZO1134","level":"Simple",},
            "Wooden stake":{"price":0,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":10,"weight":1,"B":0,"P":1,"S":0,"special":0,"source":"PZO1115","level":"Simple",},
            "Battle aspergillum":{"price":500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":4,"B":1,"P":0,"S":0,"special":"see text","source":"PZO1115","level":"Simple",},
            "Mace, light":{"price":500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":4,"B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Sickle":{"price":600,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":"trip","source":"PZO1110","level":"Simple",},
            "Traveling kettle":{"price":500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":2,"B":1,"P":0,"S":0,"special":"Monk, see text","source":"PPC:MAH","level":"Simple",},
        },'One-Handed Melee':{
            "Broken-back seax":{"price":4000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":19,"range":0,"weight":4,"B":0,"P":1,"S":1,"special":"See text","source":"PPC:MAH","level":"Exotic",},
            "Sword, bastard":{"price":3500,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":19,"range":0,"weight":6,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Exotic",},
            "Waraxe, dwarven":{"price":3000,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":8,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Exotic",},
            "Waraxe, dwarven double":{"price":6000,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":0,"S":1,"special":"see text","source":"PZO1121","level":"Exotic",},
            "Whip":{"price":100,"sDmg":"1d2","mDmg":"1d3","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":"disarm, nonlethal, reach, trip","source":"PZO1110","level":"Exotic",},
            "Knobkerrie":{"price":500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":20,"weight":4,"B":1,"P":0,"S":0,"special":"see text","source":"PPC:RTT","level":"Exotic",},
            "Rapier, spiral":{"price":8000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":18,"range":0,"weight":3,"B":0,"P":1,"S":0,"special":"blocking, disarm, see text","source":"PPZO94102","level":"Exotic",},
            "Tongi":{"price":1800,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":19,"range":0,"weight":4,"B":0,"P":1,"S":0,"special":0,"source":"PZO9468","level":"Exotic",},
            "Axe, hooked":{"price":2000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":7,"B":0,"P":0,"S":1,"special":"disarm, performance, trip","source":"PZO1118","level":"Exotic",},
            "Axe-Gauntlet, Dwarven Heavy":{"price":2100,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":5,"B":0,"P":0,"S":1,"special":"blocking, disarm","source":"PPC:HftF","level":"Exotic",},
            "Falcata":{"price":1800,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":19,"range":0,"weight":4,"B":0,"P":0,"S":1,"special":0,"source":"PZO1115","level":"Exotic",},
            "Flickmace":{"price":2000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":10,"B":1,"P":0,"S":0,"special":"reach, trip","source":"PC:GoG","level":"Exotic",},
            "Flindbar":{"price":900,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":6,"B":0,"P":1,"S":0,"special":"disarm, trip","source":"MC","level":"Exotic",},
            "Khopesh":{"price":2000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":8,"B":0,"P":0,"S":1,"special":"trip","source":"PZO1115","level":"Exotic",},
            "Ram Hammer, Dwarven":{"price":2500,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":10,"weight":5,"B":1,"P":0,"S":0,"special":0,"source":"PPC:HftF","level":"Exotic",},
            "Rhoka":{"price":500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":18,"range":0,"weight":6,"B":0,"P":0,"S":1,"special":0,"source":"PPZO9410","level":"Exotic",},
            "Sabre, sawtooth":{"price":3500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":0,"source":"PZO9226-Revised","level":"Exotic",},
            "Shotel":{"price":3000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":3,"B":0,"P":1,"S":0,"special":"performance","source":"PZO1118","level":"Exotic",},
            "Sickle-sword":{"price":2000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":4,"B":0,"P":0,"S":1,"special":"distracting, see text","source":"PPZO94102","level":"Exotic",},
            "Sword, dueling":{"price":2000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":3,"B":0,"P":0,"S":1,"special":0,"source":"PZO9226-Revised","level":"Exotic",},
            "Estoc":{"price":5000,"sDmg":"2d3","mDmg":"2d4","crit":2,"mincrit":18,"range":0,"weight":4,"B":0,"P":1,"S":0,"special":0,"source":"PZO9468","level":"Exotic",},
            "Split-blade sword":{"price":20000,"sDmg":"1d10","mDmg":"2d6","crit":2,"mincrit":20,"range":0,"weight":8,"B":0,"P":0,"S":1,"special":"Disarm, trip, see text","source":"PPC:MAH","level":"Exotic",},
            "Scizore":{"price":2000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":20,"range":0,"weight":3,"B":0,"P":1,"S":0,"special":0,"source":"PZO1118","level":"Martial",},
            "Shield, heavy":{"price":"0eial","sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":"special","B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Combat scabbard":{"price":100,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":18,"range":0,"weight":1,"B":1,"P":0,"S":0,"special":"improvised, see text","source":"PPZO9410","level":"Martial",},
            "Cutlass":{"price":1500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":4,"B":0,"P":0,"S":1,"special":0,"source":"PPZO94102","level":"Martial",},
            "Klar":{"price":1200,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":6,"B":0,"P":0,"S":1,"special":0,"source":"PZO9226-Revised","level":"Martial",},
            "Pick, heavy":{"price":800,"sDmg":"1d4","mDmg":"1d6","crit":4,"mincrit":20,"range":0,"weight":6,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Rapier":{"price":2000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":18,"range":0,"weight":2,"B":0,"P":1,"S":0,"special":"finesse","source":"PZO1110","level":"Martial",},
            "Scabbard, combat (sharpened)":{"price":1000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":1,"special":"see text","source":"PPZO9410","level":"Martial",},
            "Scimitar":{"price":1500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":18,"range":0,"weight":4,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Martial",},
            "Spiked shield, heavy":{"price":"1700/3000","sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":"special","B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Sword cane":{"price":4500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":4,"B":0,"P":1,"S":0,"special":"see text","source":"PZO1115","level":"Martial",},
            "Ankus":{"price":800,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":5,"B":0,"P":1,"S":0,"special":"disarm, trip","source":"PZO9468","level":"Martial",},
            "Battleaxe":{"price":1000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":6,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Martial",},
            "Flail, light":{"price":800,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":5,"B":1,"P":0,"S":0,"special":"disarm, trip","source":"PZO1110","level":"Martial",},
            "Longsword":{"price":1500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":4,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Martial",},
            "Manople":{"price":1700,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":4,"B":0,"P":1,"S":1,"special":"blocking, disarm","source":"PZO9468","level":"Martial",},
            "Terbutje":{"price":500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":"fragile","source":"PPZO9410","level":"Martial",},
            "Terbutje, steel":{"price":2000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":4,"B":0,"P":0,"S":1,"special":0,"source":"PPZO9410","level":"Martial",},
            "Trident":{"price":1500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":10,"weight":4,"B":0,"P":1,"S":0,"special":"brace","source":"PZO1110","level":"Martial",},
            "Warhammer":{"price":1200,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":5,"B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Gandasa":{"price":1500,"sDmg":"1d6","mDmg":"2d4","crit":3,"mincrit":20,"range":0,"weight":4,"B":0,"P":0,"S":1,"special":0,"source":"PZO9468","level":"Martial",},
            "Club, mere":{"price":200,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":1,"S":0,"special":"fragile","source":"PPZO9410","level":"Simple",},
            "Club":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":10,"weight":3,"B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Shortspear":{"price":100,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":20,"weight":3,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Mace, heavy":{"price":1200,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":8,"B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Morningstar":{"price":800,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":6,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Simple",},

        },'Ranged':{
            "Crossbow, launching":{"price":7500,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":30,"weight":8,"B":0,"P":0,"S":0,"special":"see text","source":"PPZO9410","level":"Exotic",},
            "Darts, featherweight (10)":{"price":100,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":0,"B":0,"P":0,"S":0,"special":0,"source":"PZO1134","level":"Exotic",},
            "Flask Thrower":{"price":2500,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":20,"weight":4,"B":0,"P":0,"S":0,"special":"see text","source":"PPZO94102","level":"Exotic",},
            "Lasso":{"price":10,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":5,"B":0,"P":0,"S":0,"special":"see text","source":"PZO1115","level":"Exotic",},
            "Net":{"price":2000,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":10,"weight":6,"B":0,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Exotic",},
            "Wrist launcher":{"price":20000,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":20,"weight":1,"B":0,"P":1,"S":0,"special":0,"source":"PZO1134","level":"Exotic",},
            "Crossbow, crank (heavy)":{"price":40000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":19,"range":120,"weight":12,"B":0,"P":1,"S":0,"special":0,"source":"PPC:RTT","level":"Exotic",},
            "Crossbow, repeating heavy":{"price":40000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":19,"range":120,"weight":12,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Exotic",},
            "Shuriken (5)":{"price":100,"sDmg":"1d1","mDmg":"1d2","crit":2,"mincrit":20,"range":10,"weight":0.5,"B":0,"P":1,"S":0,"special":"monk","source":"CRB","level":"Exotic",},
            "Bola":{"price":500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":10,"weight":2,"B":1,"P":0,"S":0,"special":"nonlethal, trip","source":"PZO1110","level":"Exotic",},
            "Bola, Brutal":{"price":1500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":10,"weight":2,"B":0,"P":1,"S":0,"special":"trip","source":"PZO9226-Revised","level":"Exotic",},
            "Crossbow, hand":{"price":10000,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":30,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Exotic",},
            "Pelletbow, Dwarven Light":{"price":5000,"sDmg":"1d3","mDmg":"1d4","crit":3,"mincrit":19,"range":40,"weight":4,"B":1,"P":0,"S":0,"special":0,"source":"PPC:HftF","level":"Exotic",},
            "Sling glove":{"price":500,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":50,"weight":2,"B":1,"P":0,"S":0,"special":0,"source":"PPZO9410","level":"Exotic",},
            "Sling, double":{"price":1000,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":50,"weight":1,"B":1,"P":0,"S":0,"special":"double, see text","source":"PPC:Halflings","level":"Exotic",},
            "Wrist launcher, heavy":{"price":25000,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":19,"range":30,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PZO1134","level":"Exotic",},
            "Boomerang":{"price":300,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":30,"weight":3,"B":1,"P":0,"S":0,"special":0,"source":"PZO1115","level":"Exotic",},
            "Bow, thorn":{"price":5000,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":40,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PPZO9410","level":"Exotic",},
            "Grappling hook":{"price":600,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":10,"weight":14,"B":0,"P":1,"S":0,"special":"grapple","source":"PPC:Pirates","level":"Exotic",},
            "Javelin, stormshaft":{"price":3500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":30,"weight":3,"B":0,"P":1,"S":0,"special":"See text","source":"PPZO94102","level":"Exotic",},
            "Pelletbow, Dwarven Heavy":{"price":7500,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":19,"range":60,"weight":8,"B":1,"P":0,"S":0,"special":0,"source":"PPC:HftF","level":"Exotic",},
            "Shield, throwing":{"price":5000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":20,"weight":0,"B":1,"P":0,"S":0,"special":"performance, trip","source":"PZO1118","level":"Exotic",},
            "Shrillshaft javelin":{"price":3500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":30,"weight":3,"B":0,"P":1,"S":0,"special":"see text","source":"PPC:Goblins","level":"Exotic",},
            "Sling, stitched":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":1,"B":1,"P":0,"S":0,"special":"disarm, trip","source":"PPC:Halflings","level":"Exotic",},
            "Crossbow, crank (light)":{"price":25000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":80,"weight":6,"B":0,"P":1,"S":0,"special":0,"source":"PPC:RTT","level":"Exotic",},
            "Crossbow, double":{"price":30000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":80,"weight":18,"B":0,"P":1,"S":0,"special":0,"source":"PZO1115","level":"Exotic",},
            "Crossbow, repeating light":{"price":25000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":80,"weight":6,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Exotic",},
            "Sling staff, halfling":{"price":2000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":80,"weight":3,"B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Exotic",},
            "Hornbow, orc":{"price":13000,"sDmg":"1d8","mDmg":"2d6","crit":3,"mincrit":20,"range":80,"weight":7,"B":0,"P":1,"S":0,"special":0,"source":"PPZO94102","level":"Exotic",},
            "Net, snag":{"price":3000,"sDmg":"see text","mDmg":"see text","crit":0,"mincrit":20,"range":10,"weight":10,"B":0,"P":1,"S":0,"special":"trip, see text","source":"PZO1121","level":"Exotic",},
            "Dart, jolting":{"price":10000,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":20,"weight":0.5,"B":0,"P":1,"S":0,"special":"see text","source":"PZO1121","level":"Martial",},
            "Throwing arrow cord":{"price":0,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":60,"weight":0,"B":0,"P":1,"S":0,"special":0,"source":"PPC:RTT","level":"Martial",},
            "Ammentum":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":50,"weight":1,"B":0,"P":1,"S":0,"special":"performance","source":"PZO1118","level":"Martial",},
            "Hunga munga":{"price":400,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":15,"weight":3,"B":0,"P":1,"S":0,"special":0,"source":"PPZO9410","level":"Martial",},
            "Hurlbat":{"price":800,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":10,"weight":2,"B":0,"P":1,"S":1,"special":0,"source":"PPC:RTT","level":"Martial",},
            "Shortbow":{"price":3000,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":60,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Shortbow, composite":{"price":7500,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":70,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Chakram":{"price":100,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":30,"weight":1,"B":0,"P":0,"S":1,"special":0,"source":"PZO1115","level":"Martial",},
            "Longbow":{"price":7500,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":100,"weight":3,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Longbow, composite (+0)":{"price":10000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":110,"weight":3,"B":0,"P":1,"S":0,"special":"Strength (-)","source":"PZO1110","level":"Martial",},
            "Longbow, composite (+1)":{"price":20000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":110,"weight":3,"B":0,"P":1,"S":0,"special":"Strength (12)","source":"PZO1110","level":"Martial",},
            "Longbow, composite (+2)":{"price":30000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":110,"weight":3,"B":0,"P":1,"S":0,"special":"Strength (14)","source":"PZO1110","level":"Martial",},
            "Longbow, composite (+3)":{"price":40000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":110,"weight":3,"B":0,"P":1,"S":0,"special":"Strength (16)","source":"PZO1110","level":"Martial",},
            "Longbow, composite (+4)":{"price":50000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":110,"weight":3,"B":0,"P":1,"S":0,"special":"Strength (18)","source":"PZO1110","level":"Martial",},
            "Longbow, composite (+5)":{"price":60000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":110,"weight":3,"B":0,"P":1,"S":0,"special":"Strength (20)","source":"PZO1110","level":"Martial",},
            "Pilum":{"price":500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":20,"weight":4,"B":0,"P":1,"S":0,"special":"see text","source":"PZO1115","level":"Martial",},
            "Spear-sling":{"price":5000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":"see text","weight":2,"B":0,"P":1,"S":0,"special":"see text","source":"PPC:RTT","level":"Martial",},
            "Crossbow, heavy":{"price":5000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":19,"range":120,"weight":8,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Crossbow, heavy (underwater)":{"price":10000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":19,"range":120,"weight":8,"B":0,"P":1,"S":0,"special":0,"source":"PZO1121","level":"Simple",},
            "Blowgun":{"price":200,"sDmg":"1d1","mDmg":"1d2","crit":2,"mincrit":20,"range":20,"weight":1,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Dart":{"price":50,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":20,"weight":0.5,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Sling":{"price":0,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":50,"weight":0,"B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Stingchuck":{"price":0,"sDmg":"1d3","mDmg":"1d4","crit":2,"mincrit":20,"range":10,"weight":9,"B":1,"P":0,"S":0,"special":"see text","source":"PPZO9410","level":"Simple",},
            "Javelin":{"price":100,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":30,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Stonebow":{"price":3500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":50,"weight":4,"B":1,"P":0,"S":0,"special":0,"source":"PPC:RTT","level":"Simple",},
            "Crossbow, light":{"price":3500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":80,"weight":4,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Crossbow, light (underwater)":{"price":7000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":80,"weight":4,"B":0,"P":1,"S":0,"special":0,"source":"PZO1121","level":"Simple",},

        },'Two-Handed Melee':{
            "Curve blade, elven":{"price":8000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":18,"range":0,"weight":7,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Exotic",},
            "Dorn-Dergar, dwarven":{"price":5000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":20,"range":0,"weight":15,"B":1,"P":0,"S":0,"special":"reach, see text","source":"PPZO94102","level":"Exotic",},
            "Fauchard":{"price":1400,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":18,"range":0,"weight":10,"B":0,"P":0,"S":1,"special":"reach, trip","source":"PPZO94102","level":"Exotic",},
            "Flambard":{"price":5000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":19,"range":0,"weight":6,"B":0,"P":0,"S":1,"special":"sunder","source":"PPZO9410","level":"Exotic",},
            "Orc skull ram":{"price":1500,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":20,"B":1,"P":0,"S":0,"special":"reach","source":"PZO9468","level":"Exotic",},
            "Piston maul, gnome":{"price":7000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":20,"range":0,"weight":15,"B":1,"P":0,"S":0,"special":"see text","source":"PPZO94102","level":"Exotic",},
            "Ripsaw glaive, gnome":{"price":3000,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":0,"S":1,"special":"reach, see text","source":"PPZO94102","level":"Exotic",},
            "Spear, totem":{"price":2500,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":10,"weight":6,"B":0,"P":1,"S":1,"special":"see text","source":"PZO1110","level":"Exotic",},
            "Sphinx Hammer, Dwarven":{"price":4500,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":20,"weight":8,"B":1,"P":0,"S":0,"special":0,"source":"PPC:HftF","level":"Exotic",},
            "Flying blade":{"price":4000,"sDmg":"1d10","mDmg":"1d12","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":0,"S":1,"special":"performance, reach","source":"PZO1118","level":"Exotic",},
            "Longaxe, dwarven":{"price":5000,"sDmg":"1d10","mDmg":"1d12","crit":3,"mincrit":20,"range":0,"weight":14,"B":0,"P":0,"S":1,"special":"reach","source":"PZO1121","level":"Exotic",},
            "Mancatcher":{"price":1500,"sDmg":"1d1","mDmg":"1d2","crit":2,"mincrit":20,"range":0,"weight":10,"B":0,"P":1,"S":0,"special":"grapple, reach, see text","source":"PZO1115","level":"Exotic",},
            "Crook":{"price":100,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":5,"B":1,"P":0,"S":0,"special":"reach, trip","source":"PZO9468","level":"Exotic",},
            "Garrote":{"price":300,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":1,"special":"grapple, see text","source":"PPZO9410","level":"Exotic",},
            "Scarf, bladed":{"price":1200,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":2,"B":0,"P":0,"S":1,"special":"disarm, trip","source":"PZO9226-Revised","level":"Exotic",},
            "Battle Ladder, gnome":{"price":2000,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":8,"B":1,"P":0,"S":0,"special":"trip","source":"PPZO94102","level":"Exotic",},
            "Boarding gaff":{"price":800,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":8,"B":0,"P":0,"S":1,"special":"double, reach, trip","source":"PPZO94102","level":"Exotic",},
            "Chain-hammer":{"price":3500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":20,"weight":8,"B":1,"P":0,"S":0,"special":"double, see text","source":"PPZO94102","level":"Exotic",},
            "Elven branched spear":{"price":2000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":10,"B":0,"P":1,"S":0,"special":"brace, reach","source":"PZO9468","level":"Exotic",},
            "Flailpole":{"price":1500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":10,"B":1,"P":0,"S":0,"special":"disarm, reach, trip","source":"PC:GoG","level":"Exotic",},
            "Harpoon":{"price":500,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":10,"weight":16,"B":0,"P":1,"S":0,"special":"grapple","source":"PPC:Pirates","level":"Exotic",},
            "Hammer, Gnome hooked":{"price":2000,"sDmg":"1d6","mDmg":"1d8","crit":4,"mincrit":20,"range":0,"weight":6,"B":0,"P":1,"S":0,"special":"double, trip","source":"PZO1110","level":"Exotic",},
            "Urgrosh, dwarven":{"price":5000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":1,"S":1,"special":"brace, double","source":"PZO1110","level":"Exotic",},
            "Axe, Orc Double":{"price":6000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":15,"B":0,"P":0,"S":1,"special":"double","source":"PZO1110","level":"Exotic",},
            "Double spear":{"price":2500,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":1,"S":0,"special":"double","source":"PPC:MAH","level":"Exotic",},
            "Flail, dire":{"price":9000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":10,"B":1,"P":0,"S":0,"special":"disarm, double, trip","source":"PZO1110","level":"Exotic",},
            "Sword, two-bladed":{"price":10000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":10,"B":0,"P":0,"S":1,"special":"double","source":"PZO1110","level":"Exotic",},
            "Chain, spiked":{"price":2500,"sDmg":"1d6","mDmg":"2d4","crit":2,"mincrit":20,"range":0,"weight":10,"B":0,"P":1,"S":0,"special":"disarm, trip","source":"PZO1110","level":"Exotic",},
            "Switchscythe":{"price":1800,"sDmg":"1d6","mDmg":"2d4","crit":4,"mincrit":20,"range":0,"weight":10,"B":0,"P":1,"S":1,"special":"trip","source":"PPZO94102","level":"Exotic",},
            "Giant-Sticker, Dwarven":{"price":2500,"sDmg":"1d8","mDmg":"2d6","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":1,"S":1,"special":"brace, reach","source":"PPC:HftF","level":"Exotic",},
            "Longhammer, dwarven":{"price":7000,"sDmg":"1d10","mDmg":"2d6","crit":3,"mincrit":20,"range":0,"weight":20,"B":1,"P":0,"S":0,"special":"reach","source":"PZO1121","level":"Exotic",},
            "Axe, Butchering":{"price":6500,"sDmg":"1d12","mDmg":"3d6","crit":3,"mincrit":20,"range":0,"weight":25,"B":0,"P":0,"S":1,"special":"see text","source":"PPZO94102","level":"Exotic",},
            "Boarding gaff, secondary":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":0,"B":0,"P":0,"S":1,"special":"double, reach, trip","source":"","level":"Exotic",},
            "Chain-hammer, secondary":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":20,"weight":0,"B":1,"P":0,"S":0,"special":"double, see text","source":"","level":"Exotic",},
            "Hammer, Gnome hooked, secondary":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":4,"mincrit":20,"range":0,"weight":0,"B":0,"P":1,"S":0,"special":"double, trip","source":"PZO1110","level":"Exotic",},
            "Urgrosh, dwarven, secondary":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":0,"weight":0,"B":0,"P":1,"S":1,"special":"brace, double","source":"PZO1110","level":"Exotic",},
            "Axe, Orc Double, secondary":{"price":0,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":0,"B":0,"P":0,"S":1,"special":"double","source":"PZO1110","level":"Exotic",},
            "Double spear, seconday":{"price":0,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":0,"B":0,"P":1,"S":0,"special":"double","source":"PPC:MAH","level":"Exotic",},
            "Flail, dire, secondary":{"price":0,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":0,"B":1,"P":0,"S":0,"special":"disarm, double, trip","source":"PZO1110","level":"Exotic",},
            "Sword, two-bladed, secondary":{"price":0,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":19,"range":0,"weight":0,"B":0,"P":0,"S":1,"special":"double","source":"PZO1110","level":"Exotic",},
            "Bardiche":{"price":1300,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":19,"range":0,"weight":14,"B":0,"P":0,"S":1,"special":"brace, reach, see text","source":"PZO1115","level":"Martial",},
            "Bec de corbin":{"price":1500,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":1,"S":0,"special":"brace, reach, see text","source":"PZO1115","level":"Martial",},
            "Flail, heavy":{"price":1500,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":19,"range":0,"weight":10,"B":1,"P":0,"S":0,"special":"disarm, trip","source":"PZO1110","level":"Martial",},
            "Glaive":{"price":800,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":10,"B":0,"P":0,"S":1,"special":"reach","source":"PZO1110","level":"Martial",},
            "Glaive-guisarme":{"price":1200,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":10,"B":0,"P":0,"S":1,"special":"brace, reach, see text","source":"PZO1115","level":"Martial",},
            "Greatclub":{"price":500,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":20,"range":0,"weight":8,"B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Halberd":{"price":1000,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":1,"S":1,"special":"brace, trip","source":"PZO1110","level":"Martial",},
            "Horsechopper":{"price":1000,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":1,"S":1,"special":"reach, trip","source":"PZO1121","level":"Martial",},
            "Ogre hook":{"price":2400,"sDmg":"1d8","mDmg":"1d10","crit":3,"mincrit":20,"range":0,"weight":10,"B":0,"P":1,"S":0,"special":"trip","source":"PZO9226-Revised","level":"Martial",},
            "Planson":{"price":1000,"sDmg":"1d8","mDmg":"1d10","crit":2,"mincrit":20,"range":0,"weight":10,"B":0,"P":1,"S":0,"special":"brace","source":"PZO9468","level":"Martial",},
            "Greataxe":{"price":2000,"sDmg":"1d10","mDmg":"1d12","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Martial",},
            "Hammer, lucerne":{"price":1500,"sDmg":"1d10","mDmg":"1d12","crit":2,"mincrit":20,"range":0,"weight":12,"B":0,"P":1,"S":0,"special":"brace, reach, see text","source":"PZO1115","level":"Martial",},
            "Bill":{"price":1100,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":11,"B":0,"P":0,"S":1,"special":"brace, disarm, reach, see text","source":"PZO1115","level":"Martial",},
            "Lance":{"price":1000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":10,"B":0,"P":1,"S":0,"special":"reach","source":"PZO1110","level":"Martial",},
            "Pickaxe":{"price":1400,"sDmg":"1d6","mDmg":"1d8","crit":4,"mincrit":20,"range":0,"weight":12,"B":0,"P":1,"S":0,"special":0,"source":"PAP14","level":"Martial",},
            "Spear, syringe":{"price":10000,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":20,"weight":6,"B":0,"P":1,"S":0,"special":"brace, see text","source":"PPZO9410","level":"Martial",},
            "Falchion":{"price":7500,"sDmg":"1d6","mDmg":"2d4","crit":2,"mincrit":18,"range":0,"weight":8,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Martial",},
            "Guisarme":{"price":900,"sDmg":"1d6","mDmg":"2d4","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":0,"S":1,"special":"reach, trip","source":"PZO1110","level":"Martial",},
            "Ranseur":{"price":1000,"sDmg":"1d6","mDmg":"2d4","crit":3,"mincrit":20,"range":0,"weight":12,"B":0,"P":1,"S":0,"special":"disarm, reach","source":"PZO1110","level":"Martial",},
            "Scythe":{"price":1800,"sDmg":"1d6","mDmg":"2d4","crit":4,"mincrit":20,"range":0,"weight":10,"B":0,"P":1,"S":1,"special":"trip","source":"PZO1110","level":"Martial",},
            "Earth breaker":{"price":4000,"sDmg":"1d10","mDmg":"2d6","crit":3,"mincrit":20,"range":0,"weight":14,"B":1,"P":0,"S":0,"special":0,"source":"PZO9226-Revised","level":"Martial",},
            "Greatsword":{"price":5000,"sDmg":"1d10","mDmg":"2d6","crit":2,"mincrit":19,"range":0,"weight":8,"B":0,"P":0,"S":1,"special":0,"source":"PZO1110","level":"Martial",},
            "Bayonet":{"price":500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":1,"B":0,"P":1,"S":0,"special":0,"source":"PZO1115","level":"Simple",},
            "Kumade":{"price":500,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":0,"weight":4,"B":0,"P":1,"S":0,"special":"grapple","source":"PZO9468","level":"Simple",},
            "Kumade, collapsible":{"price":1000,"sDmg":"1d4","mDmg":"1d6","crit":3,"mincrit":20,"range":0,"weight":4,"B":0,"P":1,"S":0,"special":"grapple","source":"PZO9468","level":"Simple",},
            "Lantern staff":{"price":1500,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":9,"B":1,"P":0,"S":0,"special":"See text","source":"PPZO94102","level":"Simple",},
            "Quarterstaff":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":4,"B":1,"P":0,"S":0,"special":"double, monk","source":"PZO1110","level":"Simple",},
            "Boarding pike":{"price":800,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":9,"B":0,"P":1,"S":0,"special":"brace, reach","source":"PPC:Pirates","level":"Simple",},
            "Longspear":{"price":500,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":0,"weight":9,"B":0,"P":1,"S":0,"special":"brace, reach","source":"PZO1110","level":"Simple",},
            "Spear":{"price":200,"sDmg":"1d6","mDmg":"1d8","crit":3,"mincrit":20,"range":20,"weight":6,"B":0,"P":1,"S":0,"special":"brace","source":"PZO1110","level":"Simple",},
            "Spear, boar":{"price":500,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":8,"B":0,"P":1,"S":0,"special":"brace, see text","source":"PZO1115","level":"Simple",},
            "Spear, weighted":{"price":1000,"sDmg":"1d6","mDmg":"1d8","crit":2,"mincrit":20,"range":0,"weight":8,"B":0,"P":1,"S":0,"special":"brace, double","source":"PZO9468","level":"Simple",},
            "Spear, weighted, secondary":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":8,"B":0,"P":1,"S":0,"special":"brace","source":"","level":"Simple",},
            "Quarterstaff, secondary":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":0,"B":1,"P":0,"S":0,"special":"double, monk","source":"","level":"Simple",},
            "Spear, weighted, secondary":{"price":0,"sDmg":"1d4","mDmg":"1d6","crit":2,"mincrit":20,"range":0,"weight":0,"B":0,"P":1,"S":0,"special":"brace, double","source":"","level":"Simple",},

        },'Unarmed':{
            "Gauntlet":{"price":200,"sDmg":"1d2","mDmg":"1d3","crit":2,"mincrit":20,"range":0,"weight":1,"B":1,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Unarmed strike":{"price":0,"sDmg":"1d2","mDmg":"1d3","crit":2,"mincrit":20,"range":0,"weight":0,"B":1,"P":0,"S":0,"special":"nonlethal","source":"PZO1110","level":"Simple",},

        }
    },'Ammunition':{
        'All':{
            "Crossbow bolt(s), heavy/light/hand (10)":{"price":100,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Exotic",},
            "Crossbow bolt(s), repeating, heavy/light (5)":{"price":100,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Exotic",},
            "Softstones (10)":{"price":10,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":4,"B":1,"P":0,"S":0,"special":"nonlethal","source":"PPC:Halflings","level":"Exotic",},
            "Spongestones (10)":{"price":1000,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":2,"B":0,"P":1,"S":0,"special":0,"source":"PPC:Halflings","level":"Exotic",},
            "Thorn (20)":{"price":100,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":0,"special":0,"source":"ModuleW1","level":"Exotic",},
            "Little starstones (10)":{"price":5,"sDmg":"1d1","mDmg":"1d1","crit":0,"mincrit":20,"range":0,"weight":2,"B":1,"P":0,"S":0,"special":"nonlethal","source":"PPC:Halflings","level":"Exotic",},
            "Sharpstones (10)":{"price":100,"sDmg":"1d3","mDmg":"1d4","crit":0,"mincrit":20,"range":0,"weight":5,"B":0,"P":1,"S":1,"special":0,"source":"PPC:Halflings","level":"Exotic",},
            "Arrow, smoke (1)":{"price":1000,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":0,"B":0,"P":1,"S":0,"special":"see text","source":"PZO1115","level":"Martial",},
            "Arrow, thistle (1)":{"price":100,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":0.15,"B":0,"P":1,"S":0,"special":"see text","source":"PPZO9410","level":"Martial",},
            "Arrows, blunt (20)":{"price":200,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":3,"B":1,"P":0,"S":0,"special":"see text","source":"PZO1115","level":"Martial",},
            "Arrows, common (20)":{"price":100,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":3,"B":0,"P":1,"S":0,"special":0,"source":"PZO1110","level":"Martial",},
            "Arrows, flight (20)":{"price":200,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":"see text","weight":3,"B":0,"P":1,"S":0,"special":"see text","source":"PZO1115","level":"Martial",},
            "Arrows, whistling (20)":{"price":200,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":3,"B":0,"P":0,"S":0,"special":0,"source":"PZO1118","level":"Martial",},
            "Arrow, bleeding (1)":{"price":36000,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":"see text","B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrow, durable (1)":{"price":100,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":"see text","B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrow, dye (1)":{"price":100,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":4,"B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrow, lodestone (1)":{"price":1000,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":"see text","B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrow, pheromone (1)":{"price":1500,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":"see text","B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrow, raining (1)":{"price":3000,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":"see text","B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrow, slow burn (1)":{"price":15000,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":"see text","B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrow, splintercloud (1)":{"price":2500,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":"see text","B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrow, tanglefoot (1)":{"price":2000,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":"see text","B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrow, throwing (1)":{"price":50,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":0.5,"B":0,"P":0,"S":0,"special":"see text","source":"PPC:RTT","level":"Martial",},
            "Arrow, trip (1)":{"price":2500,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":"see text","B":0,"P":0,"S":0,"special":"see text","source":"PPC:Elves","level":"Martial",},
            "Arrows/bolts, barbed (20)":{"price":200,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":3,"B":0,"P":1,"S":0,"special":"grapple","source":"PPC:RTT","level":"Martial",},
            "Arrows/bolts, incendiary (20)":{"price":1000,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":3,"B":0,"P":0,"S":0,"special":"see text","source":"PPC:RTT","level":"Martial",},
            "Arrows/bolts, pronged (20)":{"price":200,"sDmg":"see text","mDmg":"see text","crit":"","mincrit":20,"range":"see text","weight":3,"B":0,"P":0,"S":0,"special":"see text","source":"PPC:RTT","level":"Martial",},
            "Bolt(s), crossbow (10)":{"price":100,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Bolt(s), Drow poison (1)":{"price":10000,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":0.1,"B":0,"P":0,"S":0,"special":"see text","source":"PAP15","level":"Simple",},
            "Bolt(s), fire (1)":{"price":5000,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":0.1,"B":0,"P":0,"S":0,"special":"see text","source":"PAP15","level":"Simple",},
            "Bullet(s), groaning (10)":{"price":200,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":5,"B":0,"P":0,"S":0,"special":"see text","source":"PPZO9410","level":"Simple",},
            "Bullet(s), sling (10)":{"price":10,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":5,"B":0,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Bullet(s), smoke (10)":{"price":10000,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":5,"B":0,"P":0,"S":0,"special":"see text","source":"PCS","level":"Simple",},
            "Dart(s), blowgun (10)":{"price":50,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":1,"B":0,"P":0,"S":0,"special":0,"source":"PZO1110","level":"Simple",},
            "Bolt(s), acid (1)":{"price":4000,"sDmg":"0d1","mDmg":"0d1","crit":0,"mincrit":20,"range":0,"weight":0.1,"B":0,"P":0,"S":0,"special":"see text","source":"PAP15","level":"Simple",},
        }
    },'Armor':{
        'Light':{
            "Armored kilt":{"price":2000,"bonus":1,"dexBonus":6,"acPenalty":0,"ArcaneSpellFailure":0,"speed30":30,"speed20":20,"weight":10,},
            "Dancing scarves":{"price":15000,"bonus":0,"dexBonus":0,"acPenalty":0,"ArcaneSpellFailure":0,"speed30":30,"speed20":20,"weight":8,},
            "Haramaki":{"price":300,"bonus":1,"dexBonus":0,"acPenalty":0,"ArcaneSpellFailure":0,"speed30":30,"speed20":20,"weight":1,},
            "Padded":{"price":500,"bonus":1,"dexBonus":8,"acPenalty":0,"ArcaneSpellFailure":0.05,"speed30":30,"speed20":20,"weight":10,},
            "Quilted cloth":{"price":10000,"bonus":1,"dexBonus":8,"acPenalty":0,"ArcaneSpellFailure":0.1,"speed30":30,"speed20":20,"weight":15,},
            "Reinforced tunic":{"price":100,"bonus":1,"dexBonus":5,"acPenalty":0,"ArcaneSpellFailure":0.05,"speed30":30,"speed20":20,"weight":5,},
            "Silken ceremonial armor":{"price":3000,"bonus":1,"dexBonus":0,"acPenalty":0,"ArcaneSpellFailure":0,"speed30":30,"speed20":20,"weight":8,},
            "Lamellar cuirass":{"price":1500,"bonus":2,"dexBonus":4,"acPenalty":0,"ArcaneSpellFailure":0.05,"speed30":30,"speed20":20,"weight":8,},
            "Leather":{"price":1000,"bonus":2,"dexBonus":6,"acPenalty":0,"ArcaneSpellFailure":0.1,"speed30":30,"speed20":20,"weight":15,},
            "Rosewood armor":{"price":5000,"bonus":2,"dexBonus":6,"acPenalty":0,"ArcaneSpellFailure":0.1,"speed30":30,"speed20":20,"weight":15,},
            "Hell Knight leather":{"price":3000,"bonus":3,"dexBonus":5,"acPenalty":-1,"ArcaneSpellFailure":0.15,"speed30":30,"speed20":20,"weight":25,},
            "Hide shirt":{"price":2000,"bonus":3,"dexBonus":4,"acPenalty":-1,"ArcaneSpellFailure":0.15,"speed30":30,"speed20":20,"weight":18,},
            "Leaf armor":{"price":50000,"bonus":3,"dexBonus":5,"acPenalty":0,"ArcaneSpellFailure":0.15,"speed30":30,"speed20":20,"weight":20,},
            "Parade armor":{"price":2500,"bonus":3,"dexBonus":5,"acPenalty":-1,"ArcaneSpellFailure":0.15,"speed30":30,"speed20":20,"weight":20,},
            "Spider-silk bodysuit":{"price":85000,"bonus":3,"dexBonus":6,"acPenalty":-1,"ArcaneSpellFailure":0.1,"speed30":30,"speed20":20,"weight":4,},
            "Studded leather":{"price":2500,"bonus":3,"dexBonus":5,"acPenalty":-1,"ArcaneSpellFailure":0.15,"speed30":30,"speed20":20,"weight":20,},
            "Wooden":{"price":2000,"bonus":3,"dexBonus":3,"acPenalty":-1,"ArcaneSpellFailure":0.15,"speed30":30,"speed20":20,"weight":25,},
            "Chain shirt":{"price":10000,"bonus":4,"dexBonus":4,"acPenalty":-2,"ArcaneSpellFailure":0.2,"speed30":30,"speed20":20,"weight":25,},
            "Lamellar (leather)":{"price":6000,"bonus":4,"dexBonus":3,"acPenalty":-2,"ArcaneSpellFailure":0.2,"speed30":30,"speed20":20,"weight":25,},
        },'Medium':{
            "Armored coat":{"price":5000,"bonus":4,"dexBonus":3,"acPenalty":-2,"ArcaneSpellFailure":0.2,"speed30":20,"speed20":15,"weight":20,},
            "Chain coat":{"price":7500,"bonus":4,"dexBonus":5,"acPenalty":-2,"ArcaneSpellFailure":0.3,"speed30":20,"speed20":15,"weight":40,},
            "Hide":{"price":1500,"bonus":4,"dexBonus":4,"acPenalty":-3,"ArcaneSpellFailure":0.2,"speed30":20,"speed20":15,"weight":25,},
            "Ice coat":{"price":8000,"bonus":4,"dexBonus":3,"acPenalty":-2,"ArcaneSpellFailure":0.2,"speed30":20,"speed20":15,"weight":24,},
            "Do-maru":{"price":20000,"bonus":5,"dexBonus":4,"acPenalty":-4,"ArcaneSpellFailure":0.25,"speed30":20,"speed20":15,"weight":30,},
            "Kikko":{"price":25000,"bonus":5,"dexBonus":4,"acPenalty":-3,"ArcaneSpellFailure":0.2,"speed30":20,"speed20":15,"weight":25,},
            "Lamellar (horn)":{"price":10000,"bonus":5,"dexBonus":3,"acPenalty":-4,"ArcaneSpellFailure":0.25,"speed30":20,"speed20":15,"weight":30,},
            "Scale mail":{"price":5000,"bonus":5,"dexBonus":3,"acPenalty":-4,"ArcaneSpellFailure":0.25,"speed30":20,"speed20":15,"weight":30,},
            "Breastplate":{"price":20000,"bonus":6,"dexBonus":3,"acPenalty":-4,"ArcaneSpellFailure":0.25,"speed30":20,"speed20":15,"weight":30,},
            "Breastplate (agile)":{"price":40000,"bonus":6,"dexBonus":3,"acPenalty":-4,"ArcaneSpellFailure":0.25,"speed30":20,"speed20":15,"weight":25,},
            "Chainmail":{"price":15000,"bonus":6,"dexBonus":2,"acPenalty":-5,"ArcaneSpellFailure":0.3,"speed30":20,"speed20":15,"weight":40,},
            "Four mirror":{"price":12500,"bonus":6,"dexBonus":2,"acPenalty":-5,"ArcaneSpellFailure":0.3,"speed30":20,"speed20":15,"weight":45,},
            "Lamellar (steel)":{"price":15000,"bonus":6,"dexBonus":3,"acPenalty":-5,"ArcaneSpellFailure":0.25,"speed30":20,"speed20":15,"weight":35,},
            "Mountain pattern":{"price":25000,"bonus":6,"dexBonus":3,"acPenalty":-4,"ArcaneSpellFailure":0.3,"speed30":20,"speed20":15,"weight":40,},

        },'Heavy':{
            "Banded mail":{"price":25000,"bonus":7,"dexBonus":1,"acPenalty":-6,"ArcaneSpellFailure":0.35,"speed30":20,"speed20":15,"weight":35,},
            "Field plate":{"price":120000,"bonus":7,"dexBonus":1,"acPenalty":-5,"ArcaneSpellFailure":0.35,"speed30":20,"speed20":15,"weight":50,},
            "Kusari gusoku":{"price":35000,"bonus":7,"dexBonus":1,"acPenalty":-7,"ArcaneSpellFailure":0.35,"speed30":20,"speed20":15,"weight":45,},
            "Lamellar (iron)":{"price":20000,"bonus":7,"dexBonus":0,"acPenalty":-7,"ArcaneSpellFailure":0.4,"speed30":20,"speed20":15,"weight":50,},
            "Splint mail":{"price":20000,"bonus":7,"dexBonus":0,"acPenalty":-7,"ArcaneSpellFailure":0.4,"speed30":20,"speed20":15,"weight":45,},
            "Tatami-do":{"price":100000,"bonus":7,"dexBonus":3,"acPenalty":-6,"ArcaneSpellFailure":0.35,"speed30":20,"speed20":15,"weight":45,},
            "Fortress plate":{"price":210000,"bonus":8,"dexBonus":0,"acPenalty":-7,"ArcaneSpellFailure":0.4,"speed30":20,"speed20":15,"weight":75,},
            "Half-plate":{"price":60000,"bonus":8,"dexBonus":0,"acPenalty":-7,"ArcaneSpellFailure":0.4,"speed30":20,"speed20":15,"weight":50,},
            "Half-plate (agile)":{"price":85000,"bonus":8,"dexBonus":0,"acPenalty":-7,"ArcaneSpellFailure":0.4,"speed30":20,"speed20":15,"weight":55,},
            "Hell Knight half-plate":{"price":85000,"bonus":8,"dexBonus":0,"acPenalty":-7,"ArcaneSpellFailure":0.4,"speed30":20,"speed20":15,"weight":50,},
            "Lamellar (stone coat)":{"price":50000,"bonus":8,"dexBonus":0,"acPenalty":-7,"ArcaneSpellFailure":0.4,"speed30":20,"speed20":15,"weight":45,},
            "O-yoroi":{"price":170000,"bonus":8,"dexBonus":2,"acPenalty":-6,"ArcaneSpellFailure":0.35,"speed30":20,"speed20":15,"weight":45,},
            "Full plate":{"price":150000,"bonus":9,"dexBonus":1,"acPenalty":-6,"ArcaneSpellFailure":0.35,"speed30":20,"speed20":15,"weight":50,},
            "Gray Maiden plate":{"price":150000,"bonus":9,"dexBonus":1,"acPenalty":-6,"ArcaneSpellFailure":0.35,"speed30":20,"speed20":15,"weight":50,},
            "Hell Knight plate":{"price":200000,"bonus":9,"dexBonus":1,"acPenalty":-5,"ArcaneSpellFailure":0.35,"speed30":20,"speed20":15,"weight":50,},
            "Stoneplate":{"price":180000,"bonus":9,"dexBonus":1,"acPenalty":-6,"ArcaneSpellFailure":0.35,"speed30":15,"speed20":10,"weight":75,},
        },'Sheild':{
            "Buckler":{"price":500,"bonus":1,"dexBonus":0,"acPenalty":-1,"ArcaneSpellFailure":0.05,"speed30":0,"speed20":0,"weight":5,},
            "Klar":{"price":1200,"bonus":1,"dexBonus":0,"acPenalty":-1,"ArcaneSpellFailure":0.05,"speed30":0,"speed20":0,"weight":6,},
            "Madu, leather":{"price":3000,"bonus":1,"dexBonus":0,"acPenalty":-2,"ArcaneSpellFailure":0.05,"speed30":0,"speed20":0,"weight":5,},
            "Madu, steel":{"price":4000,"bonus":1,"dexBonus":0,"acPenalty":-2,"ArcaneSpellFailure":0.05,"speed30":0,"speed20":0,"weight":6,},
            "Shield, light steel":{"price":900,"bonus":1,"dexBonus":0,"acPenalty":-1,"ArcaneSpellFailure":0.05,"speed30":0,"speed20":0,"weight":6,},
            "Shield, light steel (quickdraw)":{"price":5900,"bonus":1,"dexBonus":0,"acPenalty":-2,"ArcaneSpellFailure":0.05,"speed30":0,"speed20":0,"weight":7,},
            "Shield, light wooden":{"price":300,"bonus":1,"dexBonus":0,"acPenalty":-1,"ArcaneSpellFailure":0.05,"speed30":0,"speed20":0,"weight":5,},
            "Shield, light wooden (quickdraw)":{"price":5300,"bonus":1,"dexBonus":0,"acPenalty":-2,"ArcaneSpellFailure":0.05,"speed30":0,"speed20":0,"weight":6,},
            "Shield, heavy steel":{"price":2000,"bonus":2,"dexBonus":0,"acPenalty":-2,"ArcaneSpellFailure":0.15,"speed30":0,"speed20":0,"weight":15,},
            "Shield, heavy wooden":{"price":700,"bonus":2,"dexBonus":0,"acPenalty":-2,"ArcaneSpellFailure":0.15,"speed30":0,"speed20":0,"weight":10,},
            "Shield, tower":{"price":3000,"bonus":43,"dexBonus":2,"acPenalty":-10,"ArcaneSpellFailure":0.5,"speed30":0,"speed20":0,"weight":45,},
            "Snarlshield, steel":{"price":5000,"bonus":2,"dexBonus":0,"acPenalty":-3,"ArcaneSpellFailure":0.15,"speed30":0,"speed20":0,"weight":20,},
            "Snarlshield, wooden":{"price":3700,"bonus":2,"dexBonus":0,"acPenalty":-3,"ArcaneSpellFailure":0.15,"speed30":0,"speed20":0,"weight":15,},
            "War-shield, dwarven":{"price":5000,"bonus":1,"dexBonus":0,"acPenalty":-1,"ArcaneSpellFailure":0.2,"speed30":0,"speed20":0,"weight":8,},
        }
    }
}